### ISSUE TITLE
在kubesphere中安装成功，但启动POD中报错

### ISSUE THREAD

**Issue by BigFatDog** [yunify/qingcloud-cloud-controller-manager#119]
环境：
- 青云的机器，自己安装kubespehre，3个master, 3个worker
- kubernetes 1.22
- kubesphere 3.2.0
- 按照安装指南的步骤都做了，但启动POD后，我看到了错误：

I```
1212 15:33:56.635206       1 requestheader_controller.go:244] Loaded a new request header values for RequestHeaderAuthRequestController

 W1212 15:33:56.709736       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.

 panic: runtime error: invalid memory address or nil pointer dereference

 [signal SIGSEGV: segmentation violation code=0x1 addr=0x120 pc=0x1974e44]

 

 goroutine 1 [running]:

 github.com/yunify/qingcloud-cloud-controller-manager/pkg/executor.(*QingCloudClient).ensureSecurityGroupByName(0xc000477080, 0x1e24d54, 0x11, 0x0, 0x0, 0xc0005ec960)

 	/Users/cumirror/project/go/src/github.com/yunify/qingcloud-cloud-controller-manager/pkg/executor/sg.go:137 +0xe4

 github.com/yunify/qingcloud-cloud-controller-manager/pkg/executor.NewQingCloudClient(0xc0005ea960, 0x1e312c9, 0x1a, 0x0, 0x0, 0x1b50760, 0xc0006cba00)

 	/Users/cumirror/project/go/src/github.com/yunify/qingcloud-cloud-controller-manager/pkg/executor/client.go:133 +0x85c

 github.com/yunify/qingcloud-cloud-controller-manager/pkg/qingcloud.NewQingCloud(0x206c460, 0xc00045b5d8, 0xc0004c08f8, 0x9, 0xc0004c08f0, 0x0)

 	/Users/cumirror/project/go/src/github.com/yunify/qingcloud-cloud-controller-manager/pkg/qingcloud/qingcloud.go:74 +0x2dd

 github.com/yunify/qingcloud-cloud-controller-manager/pkg/qingcloud.init.0.func1(0x206c460, 0xc00045b5d8, 0x7fff7c548a7a, 0x9, 0xc0004c0978, 0x1)

 	/Users/cumirror/project/go/src/github.com/yunify/qingcloud-cloud-controller-manager/pkg/qingcloud/qingcloud.go:56 +0x35

 k8s.io/cloud-provider.GetCloudProvider(0x7fff7c548a7a, 0x9, 0x206c460, 0xc00045b5d8, 0x0, 0x0, 0x0, 0x0)

 	/Users/cumirror/project/go/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/cloud-provider/plugins.go:86 +0xcf

 k8s.io/cloud-provider.InitCloudProvider(0x7fff7c548a7a, 0x9, 0x7fff7c548a93, 0x1e, 0x0, 0x0, 0x0, 0x0)

 	/Users/cumirror/project/go/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/cloud-provider/plugins.go:133 +0x131

 main.cloudInitializer(0xc00045b5c8, 0xc00045b5c8, 0xc0005b2228)

 	/Users/cumirror/project/go/src/github.com/yunify/qingcloud-cloud-controller-manager/cmd/main.go:73 +0x73

 k8s.io/cloud-provider/app.NewCloudControllerManagerCommand.func1(0xc0005b38c0, 0xc000571a10, 0x0, 0x3, 0x0, 0x0)

 	/Users/cumirror/project/go/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/cloud-provider/app/controllermanager.go:85 +0x27f

 github.com/spf13/cobra.(*Command).execute(0xc0005b38c0, 0xc0001a4050, 0x3, 0x3, 0xc0005b38c0, 0xc0001a4050)

 	/Users/cumirror/project/go/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/github.com/spf13/cobra/command.go:850 +0x472

 github.com/spf13/cobra.(*Command).ExecuteC(0xc0005b38c0, 0x1ef3fc0, 0xc000570fc0, 0x0)

 	/Users/cumirror/project/go/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/github.com/spf13/cobra/command.go:958 +0x375

 github.com/spf13/cobra.(*Command).Execute(...)

 	/Users/cumirror/project/go/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/github.com/spf13/cobra/command.go:895

 main.main()

 	/Users/cumirror/project/go/src/github.com/yunify/qingcloud-cloud-controller-manager/cmd/main.go:64 +0x27a
```

**Comment by BigFatDog** [comment]
[qingcloud-cloud-controller-manager.log](https://github.com/yunify/qingcloud-cloud-controller-manager/files/7699026/qingcloud-cloud-controller-manager.log)
附上完整日志，请帮忙看看

**Comment by ZengIan** [comment]
![image](https://user-images.githubusercontent.com/41040520/147822681-baae1e32-ac1a-487c-9251-23d971dd1ff5.png)
有个类似的报错，但这个是基础网络lb的问题。
我的环境是k8s 1.21.5, ks 3.2.0.部署安装没有任何问题，青云平台访问需要采用域名方式，所以要确保pod能解析api的域名(需配置coreDNS和nodelocaldns)，而不是填写ip地址，可以参考以下lbconfig和qsecret配置：
qy_access_key_id: 66666666666666666666
qy_secret_access_key: 88888888888888888888888888
zone: bj1
protocol: http
host: api.kubesphere.com #需确保pod能正确解析
port: 80
-----------------------------
zone: bj1
defaultVxNetForLB: vxnet-6666
clusterID: mycluster
userID: usr-cItestcb
