### ISSUE TITLE
servicecontroller panic

### ISSUE THREAD

**Issue by jolestar** [yunify/qingcloud-cloud-controller-manager#17]
1.  create cluster
2.  create loadbalancer type service
3.  update qingcloud-cloud-controller-manager static pod（such as: log level）,  trigger recreate pod。
4. panic
5. delete all loadbalancer type service, qingcloud-cloud-controller-manager  back to normal

```console

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1338ccd714]

goroutine 39 [running]:
github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /app/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x113
panic(0x133a7aaae0, 0x133c7252c0)
        /usr/lib/go/src/runtime/panic.go:491 +0x287
github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/api/v1/helper.LoadBalancerStatusEqual(0xc420116440, 0x0, 0xc4206b4000)
        /app/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/api/v1/helper/helpers.go:82 +0x34
github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service.(*ServiceController).createLoadBalancerIfNeeded(0xc4202b09a0, 0xc4206905a0, 0x11, 0xc4206b4000, 0xc4206a6cb8, 0x1338d37b94, 0xc42061c7a0)
        /app/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service/servicecontroller.go:300 +0x3e9
github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service.(*ServiceController).processServiceUpdate(0xc4202b09a0, 0xc42027a3b0, 0xc4206b4000, 0xc4206905a0, 0x11, 0x0, 0x0, 0x0)
        /app/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service/servicecontroller.go:230 +0x73
github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service.(*ServiceController).syncService(0xc4202b09a0, 0xc4206905a0, 0x11, 0x0, 0x0)
        /app/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service/servicecontroller.go:748 +0x3ac
github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service.(*ServiceController).worker.func1(0xc4202b09a0)
        /app/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service/servicecontroller.go:201 +0xdb
github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service.(*ServiceController).worker(0xc4202b09a0)
        /app/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service/servicecontroller.go:205 +0x2d
github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service.(*ServiceController).(github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service.worker)-fm()
        /app/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service/servicecontroller.go:183 +0x2c
github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420427c60)
        /app/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0x60
github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420427c60, 0x3b9aca00, 0x0, 0x1, 0xc420072780)
        /app/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98 +0xbf
github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420427c60, 0x3b9aca00, 0xc420072780)
        /app/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4f
created by github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service.(*ServiceController).Run
        /app/src/github.com/yunify/qingcloud-cloud-controller-manager/vendor/k8s.io/kubernetes/pkg/controller/service/servicecontroller.go:183 +0x20a
```

**Comment by jolestar** [comment]
return nil lb status at this line

https://github.com/yunify/qingcloud-cloud-controller-manager/blob/bedba97a48c085efe22b800e335fc7e927677d20/qingcloud/qingcloud_loadbalancer.go#L175

**Comment by jolestar** [comment]
fixed
